"""Add gamification study_activity table

Revision ID: a5da9b535813
Revises: e12683b61c21
Create Date: 2026-03-24 16:31:01.639963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5da9b535813'
down_revision: Union[str, Sequence[str], None] = 'e12683b61c21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('''
        CREATE TABLE IF NOT EXISTS study_activity (
            id          INTEGER PRIMARY KEY AUTOINCREMENT,
            date        DATE UNIQUE NOT NULL,
            xp          INTEGER DEFAULT 0,
            streak_days INTEGER DEFAULT 0
        )
    ''')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TABLE IF EXISTS study_activity")
    # ### end Alembic commands ###
